### ISSUE TITLE
How can I reproduce TNT-Meetingroom result?

### ISSUE THREAD

**Issue by DerKleineLi** [NVlabs/neuralangelo#14]
Hi there, thanks for publishing the code.

I'm trying to reproduce the result of Meetingroom in the tanks and temples dataset. I run `projects/neuralangelo/scripts/convert_tnt_to_json.py` to process the data and use the following config:
```yaml
_parent_: projects/neuralangelo/configs/base.yaml

model:
    object:
        sdf:
            mlp:
                inside_out: True   # True for Meetingroom.
            encoding:
                coarse2fine:
                    init_active_level: 8
    appear_embed:
        enabled: True
        dim: 8

data:
    type: projects.neuralangelo.data
    root: .../data/TNT/Meetingroom
    num_images: 371  # The number of training images.
    train:
        image_size: [835,1500]
        batch_size: 1
        subset:
    val:
        image_size: [300,540]
        batch_size: 1
        subset: 1
        max_viz_samples: 16
```

However, I only get a PSNR around 22 at iteration 300k. Do you have any suggestions to improve it?

Thank you!
