### ISSUE TITLE
Poor Performance on ScanNet

### ISSUE THREAD

**Issue by zParquet** [NVlabs/neuralangelo#39]
Thanks for you excellent work! 
I have tried it on ScanNet datsets, however, I got a totally bad results. This is the reconstruction results after 30k iters:

<img src="https://github.com/NVlabs/neuralangelo/assets/42182507/1cc896d6-7ee8-42cf-8b11-e8cd4c42d977" width=50% />

where the gt mesh is like:

<img src="https://github.com/NVlabs/neuralangelo/assets/42182507/d964affc-9750-47db-b9f6-701709ae6285" width=50% />

I haved adjusted the dataset format and config files, but I don't know whether the result is due to the method or due to some hyperparameters.
The adjusted config file is below:
```yaml
model:
    object:
        sdf:
            mlp:
                inside_out: True
                out_bias: 0.6
            encoding:
                coarse2fine:
                    init_active_level: 8
    appear_embed:
        enabled: True
        dim: 8
    background:
        enabled: False
    render:
        num_samples:
            background: 0
```
Additinally, I normalize ScanNet scene into the cube of [-0.5, 0.5], and I changed the near/far sampling to 0 and 1.5

Do you have any ideas why ScanNet appears so poor performance?
