### ISSUE TITLE
Poor results on Barn

### ISSUE THREAD

**Issue by MulinYu** [NVlabs/neuralangelo#44]
Dear authors,

Thanks for relaesing the code. I ran the code with the given tnt confige on Barn (processed folowing the guide) but the result is bad and far away from which shown in the paper. Can you please give me some advices or share the config that you used?

Thnaks alot,
Best.
Mulin

**Comment by MulinYu** [comment]
Here is the results:
![normal](https://github.com/NVlabs/neuralangelo/assets/26922343/6d98ec43-3a52-4041-b3df-651888e31ed8)
![barn](https://github.com/NVlabs/neuralangelo/assets/26922343/dba51b7f-fc12-4336-be4f-67fc79ca343d)

**Comment by mli0603** [comment]
Hi @MulinYu 

Thank you for your interest in the project!

we recently found a bug in T&T preprocessing. It was fixed in https://github.com/NVlabs/neuralangelo/commit/62483febb00c9ad4b8a17884abf9191acc6cafa9. Can you check if this fixes your issue?

**Comment by DerKleineLi** [comment]
Hi @mli0603 

I don't think the fix works, as `bounding_box` only affects the `aabb_range` in `transforms.json`, which is not used during training. 

With the latest commit I tried to train the Meetingroom and got similar result as above:
![未标题-1](https://github.com/NVlabs/neuralangelo/assets/64646379/1666f8e0-164d-4dc0-86b1-34ee1e9238b5)
from left to right: gt, render, normal, depth. This is the evaluation reslut at iteration 80k

I followed #14 to setup the hyperparameters using `grad_accum_iter`, which should match the experiment in the paper:
```yaml
_parent_: projects/neuralangelo/configs/base.yaml

max_iter: 4000000

wandb_scalar_iter: 800
wandb_image_iter: 80000
validation_iter: 40000

model:
    object:
        sdf:
            mlp:
                inside_out: True   # True for Meetingroom.
            encoding:
                coarse2fine:
                    init_active_level: 8
                    step: 40000
    appear_embed:
        enabled: True
        dim: 8

data:
    type: projects.neuralangelo.data
    root: .../data/TNT/Meetingroom
    num_images: 371  # The number of training images.
    train:
        image_size: [835,1500]
        batch_size: 16
        subset:
    val:
        image_size: [300,540]
        batch_size: 16
        subset: 16
        max_viz_samples: 16

trainer:
    grad_accum_iter: 8

optim:
    sched:
        warm_up_end: 40000
        two_steps: [2400000,3200000]
```

Do you have any intuition on how the result should look like at this iteration and what could be wrong with my experiment?

**Comment by DerKleineLi** [comment]
It seems that the bounding sphere has a wrong size in my case:
![image](https://github.com/NVlabs/neuralangelo/assets/64646379/6e166111-8b8b-46be-991e-74ab9e56d1e8)
Will try to fix that and update with the result. Thanks for the hint in the latest README :)

**Comment by mli0603** [comment]
Hi @DerKleineLi 

Good news! Glad you have found the problem.

However, I wonder if you used `preprocess_tnt.sh` to generate the bounding regions. I would expect the bounding region to work fairly well for T&T, otherwise it is a bug and I need to fix it.

**Comment by DerKleineLi** [comment]
Thanks for the comment @mli0603!

For Meetingroom I manually downloaded the images and colmap reconstruction from the official release of TNT, placed the file as described in `DATA_PROCESSING.md`, and ran
```bash
python projects/neuralangelo/scripts/convert_tnt_to_json.py --tnt_path .../data/TNT
```
For the visualization I ran `projects/neuralangelo/scripts/visualize_colmap.ipynb` with 
```python
colmap_path = ".../data/TNT/Meetingroom"
json_fname = f"{colmap_path}/transforms.json"
```

Hope it helps!

**Comment by mli0603** [comment]
Thanks @DerKleineLi 

I see. There may be an issue with the conversion. Let me look into it.

**Comment by Willyzw** [comment]
Hi, I can confirm the observed degraded results.

Sofar I have trained the Neuralangelo model on Barn and Courthouse scenes. Training logs on Wandb can be accessed here: https://api.wandb.ai/links/willyzw/whf9tz8o

I mostly followed the default configeration with the minor change to batch size: 1 for Courthouse, and 2 for Barn. As I thought this may have some impace. Any insights would be helpful!

**Comment by MulinYu** [comment]
> Hi @MulinYu
> 
> Thank you for your interest in the project!
> 
> we recently found a bug in T&T preprocessing. It was fixed in [62483fe](https://github.com/NVlabs/neuralangelo/commit/62483febb00c9ad4b8a17884abf9191acc6cafa9). Can you check if this fixes your issue?

Hello,

I've utilized the updated script to produce a new JSON file for the Barn and subsequently retrained it using a batch size of 16. However, the outcome is still unsatisfactory after 70,000 iterations. Could you pleaes share your JSON files for TNT? If I continue to obtain bad results using your JSON files, it would indicate that the preprocessing stage is not the source of the issue.
![new-barn-normal](https://github.com/NVlabs/neuralangelo/assets/26922343/5fdd07d5-52ad-4306-bc3c-f4138f9e8d84)
![new-barn](https://github.com/NVlabs/neuralangelo/assets/26922343/a06c44fd-4ec5-4587-ad05-4bb6bb39fd8d)


Best,
Mulin

**Comment by mli0603** [comment]
Thanks for this info. We are looking into this issue. We will update once we pin down the error.

**Comment by hugoycj** [comment]
@DerKleineLi @mli0603 Some updates for Meeting Room training results at 60K steps. It's :
![rgb_render_60000_ba0ad47bb40320ae50b3](https://github.com/NVlabs/neuralangelo/assets/40767265/e6b06544-cf96-41e4-9a21-b3c49a4440f9)
![media_images_val_vis_normal_60000_819909930e528679b6a5](https://github.com/NVlabs/neuralangelo/assets/40767265/91eb4b20-8e8c-40fd-8b8a-b3566ab95b18)

I use [BlenderNeuralangelo](https://github.com/mli0603/BlenderNeuralangelo) to manually regenerate the bounding_box and sphere. I have also modified the ray_num from 512 to 2048 to accelerate the training.

**Comment by DerKleineLi** [comment]
@hugoycj 
Amazing result! Could you share more details about your pipeline?
Did you use the official colmap reconstruction of TNT? How large is the bounding box? Have you modified other hyperparameters?
Thank you!

**Comment by hugoycj** [comment]
Yeap. I follow the same steps in provided convert_tnt_to_json.py scripts, followed by calculating bounding box using Blender. One interesting thing I found for Meetingroom scene is the sparse point clouds are too noisy which make the auto-generated bounding box around 2~3 times larger than the real scene, which may make it difficult to converge I guess.

Here are the updated params in transforms.json under datasets/tanks_and_temples/Meetingroom dir. I think you could replace these params directly in your JSON file and visualize it again. 
```
"aabb_scale": 16.0,
  "aabb_range": [
    [
      -7.6214215713955715,
      6.522051862701991
    ],
    [
      -3.6237776073426597,
      4.891977370864412
    ],
    [
      -11.059166537834281,
      9.311011724588386
    ]
  ],
  "sphere_center": [
    -0.5496848543467903,
    0.6340998817608761,
    -0.8740774066229475
  ],
  "sphere_radius": 11.449168401589803
```

**Comment by hugoycj** [comment]
I have also tried the colmap scripts using my own data. The results are stills far from good maybe due to the training time, but we could observe some fine detailed region is generated. 
<img width="741" alt="image" src="https://github.com/NVlabs/neuralangelo/assets/40767265/9f6a495c-d3d4-4501-bd43-84d5b778b572">

**Comment by hugoycj** [comment]
One simple suggestion for training on custom data: try to capture video in ultrawide mode, this could may the pose estimation more accurate and may be benificial to neuralangelo training.

**Comment by hugoycj** [comment]
@mli0603 
<img width="1099" alt="image" src="https://github.com/NVlabs/neuralangelo/assets/40767265/d0b838a4-78bf-4076-bb82-2d2b9b007b06">
I am curious about the dramatic drop in PSNR during 20k and 30k when training on MeetingRoom. Do you have any idea why this happen?

**Comment by DerKleineLi** [comment]
@mli0603 @hugoycj Thank you for your help. I think I found the issue:
The generated `transforms.json` by the `convert_tnt_to_json.py` points the file path to the undistorted images, instead of `"file_path": "images/xxx.jpg"`, it should be `"file_path": "dense/images/xxx.jpg"`
Having this fixed I'm getting good result at iteration 15k with batch size 16, grad_accum_iter=1 on 1 gpu:
![image](https://github.com/NVlabs/neuralangelo/assets/64646379/272e9524-81f8-497f-98ec-08ae8001f2de)
![image](https://github.com/NVlabs/neuralangelo/assets/64646379/2b0a2fd4-1910-471c-bcc5-32d69b1b0c2e)

**Comment by MulinYu** [comment]
> @mli0603 @hugoycj Thank you for your help. I think I found the issue: The generated `transforms.json` by the `convert_tnt_to_json.py` points the file path to the uncalibrated images. Instead of `"file_path": "images/xxx.jpg"`, it should be `"file_path": "dense/images/xxx.jpg"` Having this fixed I'm getting good result at iteration 15k with batch size 16, grad_accum_iter=1 on 1 gpu: ![image](https://user-images.githubusercontent.com/64646379/262338859-272e9524-81f8-497f-98ec-08ae8001f2de.png) ![image](https://user-images.githubusercontent.com/64646379/262338896-2b0a2fd4-1910-471c-bcc5-32d69b1b0c2e.png)

Dear @DerKleineLi 

You are right, the generated json file let the dataloader read the images before undistortion. I also get better results on Barn after changing the image path to 'dense/images'.


Thanks alot.
Best.
Mulin

**Comment by chenhsuanlin** [comment]
Update: we have updated the data structure of the COLMAP artifacts in the latest `main` branch to avoid confusion. We are now storing the raw images in `images_raw` and the undistorted images in `images` (the final images for Neuralangelo). The `dense` folder has also been removed. Please see the new [data preparation](https://github.com/NVlabs/neuralangelo/blob/main/DATA_PROCESSING.md) for details on the new structure.

**Comment by mli0603** [comment]
The tanks and temples preprocessing script has been updated (see https://github.com/NVlabs/neuralangelo/commit/54172deb11660fd6c64d727e600f0201b002347a) to fix the above bug and reflect the latest changes of data preprocessing.

**Comment by DerKleineLi** [comment]
Hi all, I still need some help with the TNT dataset. Here's the result I get using the latest commit:
![image](https://github.com/NVlabs/neuralangelo/assets/64646379/5d76f932-7c53-4dc2-8419-21d40d022e4d)
It's much blurrier than the paper's result. If anyone have reached a better result, it would be great to let me know your settings and results. Thanks in advance! 

@hugoycj I wonder if you have trained the Meeetingroom till the end, how was the result? I also followed your pipeline a bit and here's what I got at iteration 60k:
![image](https://github.com/NVlabs/neuralangelo/assets/64646379/0ad3dd02-6caa-47bf-9400-d5f8d96c95bf)
Here's the config:
```yaml
_parent_: projects/neuralangelo/configs/base.yaml

model:
    object:
        sdf:
            mlp:
                inside_out: True   # True for Meetingroom.
            encoding:
                coarse2fine:
                    init_active_level: 8
    appear_embed:
        enabled: True
        dim: 8
    render:
        rand_rays: 2048

data:
    type: projects.neuralangelo.data
    root: .../data/TNT/Meetingroom
    num_images: 371  # The number of training images.
    train:
        image_size: [835,1500]
        batch_size: 1
        subset:
    val:
        image_size: [300,540]
        batch_size: 1
        subset: 1
        max_viz_samples: 16
```
The result is very different from yours. Could you check whether the config fits yours? If so, the problem could lie in the data preprocessing, could you then share the complete `transforms.json` file? Only the global parameters are not enough because as you change the bbox, the transform of each frame would also change.

Another question regarding the blender plugin: There are limits as we change the size of the bbox. The image shows the smallest possible bbox of the plugin. I wonder if this is the same as in your case and have you edited the script to allow smaller bboxes?
![image](https://github.com/NVlabs/neuralangelo/assets/64646379/72caf82a-5560-42ab-9a71-e26d3de7863c)
